### ISSUE TITLE
Docker build: testui Cannot find module 'vue-template-compiler'

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1315]
1. git pull
2. ❯ git status
On branch master
Your branch is up to date with 'origin/master'.

3. docker-compose build

Error message:

```
 => CACHED [testui 2/7] RUN npm install -g http-server                                                                                   0.0s
 => CACHED [testui 3/7] WORKDIR /app                                                                                                     0.0s
 => CACHED [testui 4/7] COPY package*.json ./                                                                                            0.0s
 => CACHED [testui 5/7] RUN npm install                                                                                                  0.0s
 => CACHED [testui 6/7] COPY . .                                                                                                         0.0s
 => ERROR [testui 7/7] RUN npm run build                                                                                                 1.3s
------
 > [testui 7/7] RUN npm run build:
0.338
0.338 > test-ui@0.1.0 build
0.338 > vue-cli-service build
0.338
0.634 Browserslist: caniuse-lite is outdated. Please run:
0.634   npx update-browserslist-db@latest
0.634   Why you should do it regularly: https://github.com/browserslist/update-db#readme
0.640 All browser targets in the browserslist configuration have supported ES module.
0.640 Therefore we don't build two separate bundles for differential loading.
0.640
0.651
0.652 -  Building for production...
1.278  ERROR  Error: Cannot find module 'vue-template-compiler'
1.278         Require stack:
1.278         - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/compiler.js
1.278         - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js
1.278         - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin.js
1.278         - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/index.js
1.278         - /app/node_modules/@vue/cli-service/lib/config/base.js
1.278         - /app/node_modules/@vue/cli-service/lib/Service.js
1.278         - /app/node_modules/@vue/cli-service/bin/vue-cli-service.js
1.278 Error: Cannot find module 'vue-template-compiler'
1.278 Require stack:
1.278 - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/compiler.js
1.278 - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js
1.278 - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin.js
1.278 - /app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/index.js
1.278 - /app/node_modules/@vue/cli-service/lib/config/base.js
1.278 - /app/node_modules/@vue/cli-service/lib/Service.js
1.278 - /app/node_modules/@vue/cli-service/bin/vue-cli-service.js
1.278     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
1.278     at Function.resolve (node:internal/modules/helpers:136:19)
1.278     at loadFromContext (/app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/compiler.js:30:26)
1.278     at loadTemplateCompiler (/app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/compiler.js:37:12)
1.278     at exports.resolveCompiler (/app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/compiler.js:25:23)
1.278     at VueLoaderPlugin.apply (/app/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js:144:22)
1.278     at createCompiler (/app/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:73:12)
1.278     at create (/app/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:134:16)
1.278     at webpack (/app/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:142:47)
1.278     at f (/app/node_modules/@vue/cli-service/node_modules/webpack/lib/index.js:64:16)
1.278     at /app/node_modules/@vue/cli-service/lib/commands/build/index.js:200:5
1.278     at new Promise (<anonymous>)
1.278     at build (/app/node_modules/@vue/cli-service/lib/commands/build/index.js:199:10)
1.278     at async /app/node_modules/@vue/cli-service/lib/commands/build/index.js:69:7
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```
Did I something wrong?

**Desktop (please complete the following information):**
 - OS: Latest MacOs
- Docker: Latest version

**Comment by bpamiri** [comment]
@michaeldiederich I will reproduce your steps in a few minutes and let you know the results. 

But in the meantime have you tried simply issuing the command again but this time without the dash:
```docker compose up```

I have also found that when building the docker images for the first time, I tend to get some errors or timeouts as it tries to build all the individual containers. I sometimes have to issue the command a few times to get all the individual containers to build successfully.

**Comment by michaeldiederich** [comment]
Same error message and I tried it multiple times

**Comment by bpamiri** [comment]
@michaeldiederich give it another try. I got the `testui` to build now. Still having some issues with some of the CFEngine containers building but I suspect that is an issue with ForgeBox at the moment. The Lucee6 container builds fine for me right now.

Rewriting the testui as a stand alone CFML app with perhaps some HTMX and Alpine thrown in for interactivity is on my todo list.

**Comment by michaeldiederich** [comment]
Works fine, thank you!
