### ISSUE TITLE
Onsessionend causing java heap space exhaustion and server hang

### ISSUE THREAD

**Issue by edthetechie** [cfwheels/cfwheels#1439]
We had a server outage over the weekend and it seems one of the websites used up all the heap space resources. xByte support said it was something to do with onsessionend.cfm in the wheels folder. I don't use onsessionend at all for this client site so I figured I should post it here. It could be that this is a problem with Adobe CF2023 and/or Windows. I'm not necessarily expecting a solution but I figured it made sense to submit the issue. Below is the the email I got from Dakota at xByte:

After getting the site back online we began reviewing the diagnostics we collected from the server and we discovered that your Java heap space region was exhausted. The specific thread that appears to be responsible for the Java heap space exhaustion has been listed below for your review:
 
"scheduler-0" #94 prio=5 os_prio=0 cpu=4291359.38ms elapsed=760234.94s tid=0x000001c0dcb688e0 nid=0x242c runnable [0x00000052edafc000]
java.lang.Thread.State: RUNNABLE
at java.io.WinNTFileSystem.getLength(java.base@17.0.9/Native Method)
at java.io.File.length(java.base@17.0.9/File.java:1004)
at coldfusion.runtime.TemplateProxyFactory._isBaseComponentEmpty(TemplateProxyFactory.java:751)
at coldfusion.runtime.TemplateProxyFactory.isBaseComponentEmpty(TemplateProxyFactory.java:728)
at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:459)
at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:286)
at coldfusion.runtime.ComponentTemplateProxyCache.getTemplateProxyFromChildPath(ComponentTemplateProxyCache.java:117)
at coldfusion.runtime.TemplateProxy.checkFinalMethodOverrideRecursively(TemplateProxy.java:1607)
at coldfusion.runtime.TemplateProxy.validateFinalMethodOverride(TemplateProxy.java:1836)
at coldfusion.runtime.TemplateProxy.validateComponent(TemplateProxy.java:1850)
at coldfusion.runtime.TemplateProxy.verifyInterfacesImpl(TemplateProxy.java:2265)
at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:89)
at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:56)
at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:101)
at coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:92)
at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:3858)
at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:127)
at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:80)
at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:158)
at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:80)
at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:158)
at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:80)
at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:158)
at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:80)
at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:158)
at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:80)
at coldfusion.runtime.CFPage.Duplicate(CFPage.java:10894)
at cfcfml2ecfm371205507$func$INVOKE.runFunction(\\website_root\wheels\global\cfml.cfm:159)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:629)
at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:559)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:522)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:469)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:444)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:687)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4797)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4778)
at cfcfml2ecfm371205507$func$SIMPLELOCK.runFunction(\\website_root\wheels\global\cfml.cfm:37)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:629)
at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:559)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:522)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:469)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:444)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:687)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4797)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4778)
at cfonsessionend2ecfm671182544$funcONSESSIONEND.runFunction(\\website_root\wheels\events\onsessionend.cfm:9)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:629)
at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:559)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:522)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:469)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:444)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:316)
at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:975)
at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:921)
at coldfusion.cfc.CFCProxyFilter.invokeAppEvent(CFCProxyFilter.java:102)
- locked <0x00000007d12999c8> (a coldfusion.runtime.CFDummyComponent)
at coldfusion.cfc.CFCProxyFilter.invoke(CFCProxyFilter.java:43)
at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
at coldfusion.cfc.CFCProxy.doInvoke(CFCProxy.java:331)
at coldfusion.cfc.CFCProxy.invoke(CFCProxy.java:305)
at coldfusion.runtime.AppEventInvoker.onSessionEnd(AppEventInvoker.java:489)
at coldfusion.runtime.SessionTracker.invokeOnSessinEnd(SessionTracker.java:292)
at coldfusion.runtime.SessionTracker.cleanUp(SessionTracker.java:275)
at coldfusion.runtime.SessionTracker.access$000(SessionTracker.java:43)
at coldfusion.runtime.SessionTracker$SessionCleanUpAgent.run(SessionTracker.java:484)
at coldfusion.scheduling.ThreadPool.run(ThreadPool.java:260)
at coldfusion.scheduling.WorkerThread.run(WorkerThread.java:71)
 
 
It appears this is getting invoked by your onsessionend.cfm template and a hang is occurring. There were 28 similar threads hanging that were invoked by onsessionend.cfm. Please review this script and make sure it is functioning as expected and that there are no unexpected hangs within your onsessionend.cfm logic.

**Comment by zainforbjs** [comment]
@edthetechie It sounds like the issue might be specific to the server setup or one of the websites running on it, especially since you’re not using `onSessionEnd.cfm` in your app. Wheels does include a default version of that file, but it shouldn’t cause problems on its own. Please take the latest v3.0 and review. 
If you find anything in the framework that might be contributing to the issue, feel free to share — we’re happy to take a look.
