### ISSUE TITLE
imageTag and ".ico"

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#830]
Hi,

`#GetReadableImageFormats()#` says, that ico is a valid file extension for images. In wheels, it throws an error:

string            Message 
                    string can not read in
file /home/project/images/folder/64x64.ico 
                StackTrace 
    
string can not read in file /home/project/images/folder/64x64.ico
at lucee.runtime.img.Image.(Image.java:221):221
at lucee.runtime.img.Image.createImage(Image.java:1458):1458
at lucee.runtime.tag.Image.doStartTag(Image.java:334):334
at global.cfml_cfm$cf.udfCall1(/wheels/global/cfml.cfm:44):44
at global.cfml_cfm$cf.udfCall(/wheels/global/cfml.cfm):-1
at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775
at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:774):774
at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1609):1609
at view.assets_cfm$cf.udfCall(/wheels/view/assets.cfm:207):207

Tested with lucee 4.5.5 and 5.2.4. File Permissions are the same as for png/jpg. If you need further input, please don't hesitate to get in touch with me.

**Comment by perdjurner** [comment]
Can you read it using the cfimage tag?

**Comment by michaeldiederich** [comment]
Well, no. I created a bug issue at lucee: https://luceeserver.atlassian.net/browse/LDEV-1620
I guess there is nothing wheels can do, so you can close the issue.
