### ISSUE TITLE
Variable APPLICATION is undefined

### ISSUE THREAD

**Issue by dbelanger** [cfwheels/cfwheels#879]
On every request, a call is made to include plugins/standalone/injection.cfm.  That file checks for the presence of things in the application scope.  However, on a session's end, that scope isn't available.

I believe this hasn't been reported because the user isn't around to see the session ending.  However, in an application with a lot of short sessions (such as an API), the errors start to accumulate in the logs.

The following is well describe in the google groups post: https://groups.google.com/forum/#!topic/cfwheels/P4SqL5h9Zkk

The following is the trace that leads to the error:

**coldfusion.runtime.UndefinedVariableException: Variable APPLICATION is undefined.**
 at coldfusion.runtime.CfJspPage._get(CfJspPage.java:351)
 at coldfusion.runtime.CfJspPage._get(CfJspPage.java:330)
 at coldfusion.runtime.CfJspPage._get(CfJspPage.java:317)
 at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1798)
 at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1760)
 **at cfinjection2ecfm2053640414.runPage(Z:\MYPROJECTDIRECTORY\wheels\plugins\standalone\injection.cfm:5)**
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
 at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
 at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
 at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3696)
 **at cfModel2ecfc394272461.runPage(Z:\MYPROJECTDIRECTORY\wheels\Model.cfc:4)**
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:542)
 at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:251)
 at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:377)
 at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:251)
 at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:377)
 at coldfusion.runtime.TemplateProxyFactory.resolveNameForDuplicate(TemplateProxyFactory.java:168)
 at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:47)
 at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:72)
 at coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:68)
 at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2495)
 at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
 at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
 at coldfusion.runtime.Struct.duplicate(Struct.java:210)
 at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
 at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
 at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:142)
 at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
 at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:142)
 at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
 at coldfusion.runtime.CFPage.Duplicate(CFPage.java:6698)
 **at cfcfml2ecfm631766577$func$INVOKE.runFunction(Z:\MYPROJECTDIRECTORY\wheels\global\cfml.cfm:157)**
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
 **at cfcfml2ecfm631766577$func$SIMPLELOCK.runFunction(Z:\MYPROJECTDIRECTORY\wheels\global\cfml.cfm:33)**
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
 at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
 at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
 **at cfonsessionend2ecfm543644058$funcONSESSIONEND.runFunction(Z:\MYPROJECTDIRECTORY\wheels\events\onsessionend.cfm:5)**
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
 at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:425)
 at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
 at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
 at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
 at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:234)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:650)
 at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:596)
 at coldfusion.cfc.CFCProxyFilter.invokeAppEvent(CFCProxyFilter.java:102)
 at coldfusion.cfc.CFCProxyFilter.invoke(CFCProxyFilter.java:43)
 at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
 at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
 at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
 at coldfusion.cfc.CFCProxy.doInvoke(CFCProxy.java:328)
 at coldfusion.cfc.CFCProxy.invoke(CFCProxy.java:302)
 at coldfusion.runtime.AppEventInvoker.onSessionEnd(AppEventInvoker.java:462)
 at coldfusion.runtime.SessionTracker.invokeOnSessinEnd(SessionTracker.java:292)
 at coldfusion.runtime.SessionTracker.cleanUp(SessionTracker.java:275)
 at coldfusion.runtime.SessionTracker.access$000(SessionTracker.java:43)
 at coldfusion.runtime.SessionTracker$SessionCleanUpAgent.run(SessionTracker.java:484)
 at coldfusion.scheduling.ThreadPool.run(ThreadPool.java:260)
 at coldfusion.scheduling.WorkerThread.run(WorkerThread.java:71)

**Comment by neokoenig** [comment]
Thanks for your detective work @dbelanger !

**Comment by andybellenie** [comment]
Yes, great catch.

**Comment by dbelanger** [comment]
Sorry for the messy history - I'll stop putting the issue number in the commit message and only put it in the pull request from now on.  I didn't know it would should up like this (I redid the branch 3 times and deleted the old ones but still, the commits are in the history here)

**Comment by perdjurner** [comment]
No problem :)
