### ISSUE TITLE
Error Could not initialize class cfhelpers2ecfm924268621

### ISSUE THREAD

**Issue by bdensmore** [cfwheels/cfwheels#911]
We recently migrated our CFWheels 1.4.5 app to CF2018 and running into an issue in just one section. I can't seem to figure out what the root cause is. 

I'm constantly getting a 500 error and the application.log file is showing the following:

Could not initialize class cfhelpers2ecfm924268621 The specific sequence of files included or processed is: /Applications/XAMPP/xamppfiles/htdocs/myapp/rewrite.cfm , line: 111

When I look in the coldfusion-error.log file I am seeing this:

```
Exception thrown by error-handling template:
coldfusion.runtime.EventHandlerException: Event handler exception.
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:319)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:500)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:96)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:226)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class cfhelpers2ecfm924268621
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:587)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4083)
	at cfroot2ecfm1813729637.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/root.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfinternal2ecfm725062293$func$CREATEOBJECTFROMROOT.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/global/internal.cfm:576)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850)
	at cfinitialization2ecfm146905643$func$CREATECONTROLLEROBJECT.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/controller/initialization.cfm:11)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357)
	at cfpublic2ecfm1264909641$funcCONTROLLER.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/global/public.cfm:180)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850)
	at cfrequest2ecfm80980622$func$REQUEST.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/dispatch/request.cfm:197)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357)
	at cfindex2ecfm48445621.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/index.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfrewrite2ecfm766967210.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/rewrite.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfonrequest2ecfm530319150$funcONREQUEST.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/events/onrequest.cfm:1)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:115)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:308)
	... 45 more
Dec 04, 2018 3:01:50 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [CfmServlet] in context with path [] threw exception [ROOT CAUSE: 
coldfusion.runtime.EventHandlerException: Event handler exception.
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:319)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:500)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:96)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:226)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class cfhelpers2ecfm924268621
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:587)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4083)
	at cfroot2ecfm1813729637.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/root.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfinternal2ecfm725062293$func$CREATEOBJECTFROMROOT.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/global/internal.cfm:576)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850)
	at cfinitialization2ecfm146905643$func$CREATECONTROLLEROBJECT.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/controller/initialization.cfm:11)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357)
	at cfpublic2ecfm1264909641$funcCONTROLLER.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/global/public.cfm:180)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850)
	at cfrequest2ecfm80980622$func$REQUEST.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/dispatch/request.cfm:197)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357)
	at cfindex2ecfm48445621.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/index.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfrewrite2ecfm766967210.runPage(/Applications/XAMPP/xamppfiles/htdocs/myapp/rewrite.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:729)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4082)
	at cfonrequest2ecfm530319150$funcONREQUEST.runFunction(/Applications/XAMPP/xamppfiles/htdocs/myapp/wheels/events/onrequest.cfm:1)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:552)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:483)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:446)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:397)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:370)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:286)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:115)
	at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:308)
	... 45 more
```

If anyone might have any insight as to what the issue is and the best way to go about fixing it, I would greatly appreciate it.

**Comment by neokoenig** [comment]
Pretty sure 1.4.x hasn't been tested on CF2018 - might be worth asking if anyone on the mailing list has it running..?

**Comment by ellor1138** [comment]
Hi!

I am in the process of transferring all my CFWheels websites (about 20) to
ColdFusion 2018. I am halfway done and so far all the websites are 1.4.x
and are working perfectly.

We are running ColdFusion 2018 with IIS 10 and MSSQL 2017.


Simon

**Comment by neokoenig** [comment]
@bdensmore - Closing this, please feel free to re-open
